services:
  - type: web
    name: quiz-app
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # User needs to set this in Render dashboard
      - key: JWT_SECRET
        sync: false # User needs to set this in Render dashboard 